```{r}
library(readr)
genedata <- read_csv("data/KEGG_diff_same_detail_gene_all.csv")
```

```{r}
library(clusterProfiler)
gene_symbols <- genedata$human_SYMBOL
```

```{r}
converted_data_UNIPROT <- bitr(geneID = gene_symbols, 
                            fromType = "SYMBOL", 
                            toType = "UNIPROT",
                            OrgDb = "org.Hs.eg.db", 
                            drop = TRUE)
```

```{r}
converted_data <- bitr_kegg(geneID = converted_data_UNIPROT$UNIPROT, 
                            fromType = "uniprot", 
                            toType = "kegg", 
                            organis = "hsa",
                            drop = TRUE)
```

```{r}
merged_data <- merge(converted_data, converted_data_UNIPROT,by.y = "UNIPROT", by.x = "uniprot", all = TRUE)
```

```{r}
library(dplyr)
filtered_data <- dplyr::distinct(merged_data, SYMBOL, .keep_all = TRUE)   # 按symbol列去除重复值，并保留其他列的第一个值
```

```{r}
preprocessed_data <-  merge(filtered_data, genedata,by.y = "human_SYMBOL", by.x = "SYMBOL", all = TRUE)

```

```{r}
preprocessed_data <- preprocessed_data[, !names(preprocessed_data) %in% "...1"]
```
```{r}
final_data
```

```{r}
final_data = dplyr::distinct(preprocessed_data, kegg, .keep_all = TRUE)
final_data = dplyr::filter(final_data, kegg != "NA", )
final_data = dplyr::filter(final_data, human_sig != "none"| mouse_sig != "none")
final_data <- final_data[, !names(final_data) %in% "Description"]
```

```{r}
write.table(final_data,"data/final_data.csv",row.names=FALSE,col.names=TRUE,sep=",")
```


